#!/bin/bash
if hash python3 || hash python
    echo "python is found"
    echo "Setting up..."
    sudo chmod -R 755 $(pwd)/
    $(pwd)/scripts/env
    $(pwd)/scripts/installation
    exit 0
then
    echo "python is not installed"
    exit 1
fi

ver=$(python -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$ver" -lt "27" ]; then
    echo "This script requires python 2.7 or greater"
    exit 1
fi